<?php

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'title' => 'Information Session',
                'inst_id' => 4,
                'date' => '2020-10-28',
                'timezone' => 'Europe/London',
                'start_time' => '09:00',
                'end_time' => '10:00',
                'start_utc' => '2020-10-28 09:00:00',
                'end_utc' => '2020-10-28 10:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 1,
                "user_id" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => 'Welcome to UEA',
                'inst_id' => 4,
                'date' => '2020-11-28',
                'timezone' => 'Europe/London',
                'start_time' => '10:00',
                'end_time' => '11:00',
                'start_utc' => '2020-11-28 10:00:00',
                'end_utc' => '2020-11-28 11:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 3,
                "user_id" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => 'Information Session',
                'inst_id' => 4,
                'date' => '2020-07-14',
                'timezone' => 'Europe/London',
                'start_time' => '09:00',
                'end_time' => '10:00',
                'start_utc' => '2020-07-14 09:00:00',
                'end_utc' => '2020-07-14 10:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 5,
                "user_id" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => "PG study at King's",
                'inst_id' => 5,
                'date' => '2020-12-08',
                'timezone' => 'Europe/London',
                'start_time' => '09:00',
                'end_time' => '10:00',
                'start_utc' => '2020-12-08 09:00:00',
                'end_utc' => '2020-12-08 10:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 3,
                "user_id" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => 'Information Session',
                'inst_id' => 5,
                'date' => '2020-10-03',
                'timezone' => 'Europe/London',
                'start_time' => '10:00',
                'end_time' => '11:00',
                'start_utc' => '2020-10-03 10:00:00',
                'end_utc' => '2020-10-03 11:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 1,
                "user_id" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => 'Campus Life in Northumbria',
                'inst_id' => 6,
                'date' => '2020-11-28',
                'timezone' => 'Europe/London',
                'start_time' => '09:00',
                'end_time' => '10:00',
                'start_utc' => '2020-11-28 09:00:00',
                'end_utc' => '2020-11-28 10:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 3,
                "user_id" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                'title' => 'Information Session',
                'inst_id' => 6,
                'date' => '2020-12-03',
                'timezone' => 'Europe/London',
                'start_time' => '09:00',
                'end_time' => '10:00',
                'start_utc' => '2020-12-03 09:00:00',
                'end_utc' => '2020-12-03 10:00:00',
                "description" => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
                "image" => NULL,
                "capacity_id" => 1,
                "status_id" => 3,
                "user_id" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ];
                DB::table('events')->insert($data);
    }
}
